/**
 * External dependencies
 */
var keyMirror = require( 'key-mirror' );

module.exports.actions = keyMirror( {
	ADD_ACCOUNT_RECOVERY_EMAIL: null,
	CANCEL_ACCOUNT_RECOVERY_EMAIL: null,
	SAVE_ACCOUNT_RECOVERY_EMAIL: null,
	RECEIVE_SAVED_ACCOUNT_RECOVERY_EMAIL: null,
	DELETE_ACCOUNT_RECOVERY_EMAIL: null,
	RECEIVE_DELETED_ACCOUNT_RECOVERY_EMAIL: null,
	EDIT_ACCOUNT_RECOVERY_PHONE: null,
	CANCEL_ACCOUNT_RECOVERY_PHONE: null,
	SAVE_ACCOUNT_RECOVERY_PHONE: null,
	RECEIVE_SAVED_ACCOUNT_RECOVERY_PHONE: null,
	VERIFY_ACCOUNT_RECOVERY_PHONE: null,
	RECEIVE_VERIFIED_ACCOUNT_RECOVERY_PHONE: null,
	DELETE_ACCOUNT_RECOVERY_PHONE: null,
	RECEIVE_DELETED_ACCOUNT_RECOVERY_PHONE: null,
	DISMISS_ACCOUNT_RECOVERY_EMAILS_NOTICE: null,
	DISMISS_ACCOUNT_RECOVERY_PHONE_NOTICE: null
} );

module.exports.steps = keyMirror( {
	RECOVERY_EMAIL: null,
	ADD_RECOVERY_EMAIL: null,
	RECOVERY_PHONE: null,
	EDIT_RECOVERY_PHONE: null,
	VERIFY_RECOVERY_PHONE: null
} );
